run:
  name: "qwen3_600M_rlvr_baseline_DAPO"
  mode: "rlvr"

model:
  type: "hf_causal"
  id: "outputs/qwen_600M_sft_deepthought_math_optimal"
  dtype: "bfloat16"
  gradient_checkpointing: true

tokenizer:
  type: "hf"
  id: "Qwen/Qwen3-0.6B-Base"

data:
  type: "rlvr_math"
  source: "hf"
  train_path: "allenai/RLVR-GSM-MATH-IF-Mixed-Constraints"
  name: null
  max_prompt_len: 512
  num_proc: 12

grpo:
  reward_function: "dapo_advanced"
  num_generations: 8
  max_prompt_length: 512
  max_completion_length: 768
  beta: 0.001
  scale_rewards: "group"
  loss_type: "dapo"
  epsilon: 0.2
  temperature: 0.8
  top_p: 0.95
  top_k: 0
  use_vllm: true
  vllm_mode: "colocate"
  vllm_gpu_memory_utilization: 0.5
  vllm_enable_sleep_mode: false

training:
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8

  learning_rate: 1.0e-5
  warmup_steps: 40
  max_steps: 813

  logging_steps: 10
  save_steps: 200
  eval_steps: 200

  bf16: true

  output_dir: "outputs/qwen3_600M_rlvr_baseline_DAPO"

wandb:
  tags: ["qwen3-0.6b", "rlvr", "dapo", "gsm8k-math-if", "baseline", "single-stage"]
